name: Deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
    commit_message:
      - "deploy:"

permissions: write-all

jobs:
  push-to-production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Git authentication
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:${{ secrets.GITBOT }}@github.com/${{ github.repository }}.git

      - name: Push master to production
        run: |
          git fetch --unshallow
          git checkout production
          git merge master --no-edit
          git push origin production
